options:
  logging: LEGACY

substitutions:
  _PROJECT_ID: storynook-491620
  _SERVICE_NAME: storynook-api
  _REGION: us-central1
  _REPOSITORY: storynook
  _IMAGE_NAME: storynook-api
  _APP_ENV: prod
  _PROD_API_TOKEN_SECRET: storynook-prod-api-token
  _RUNTIME_SERVICE_ACCOUNT: 496014817869-compute@developer.gserviceaccount.com

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --service-account ${_RUNTIME_SERVICE_ACCOUNT} \
          --set-env-vars APP_ENV=${_APP_ENV} \
          --set-secrets PROD_API_TOKEN=${_PROD_API_TOKEN_SECRET}:latest

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA